apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: mlops
type: Opaque
stringData:
  # PostgreSQL credentials
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow123
  POSTGRES_DB: airflow
  # Airflow admin credentials
  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: admin123
  AIRFLOW_ADMIN_EMAIL: admin@example.com
  # Fernet key for encrypting passwords in DB (generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
  AIRFLOW__CORE__FERNET_KEY: "81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs="
  # Secret key for API (moved from webserver in Airflow 3.x)
  AIRFLOW__API__SECRET_KEY: "a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08="
